name: Pull Request indication
description: This is an action to indicate new pull requestes
branding:
  icon: 'git-pull-request'
  color: 'yellow'

on:
  pull_request

runs:
    env:
      Greeting: Hello
    steps:
      - name: "Indicating during new pull request"
        run: echo "$Greeting $First_Name !. You have one new pull request"
        env:
          First_Name: codester
