name: Pull Request indication

on:
  pull_request

jobs:
  indication_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Indicating during new pull request"
        run: echo "$Greeting $First_Name !. You have one new pull request"
        env:
          First_Name: codester
