name: Pull Request indication
description: This is an action to indicate new pull requestes
branding:
  icon: 'git-pull-request'
  color: 'yellow'

runs:
  using: "composite"
  steps: 
    - name: Indicating new pull request
      shell: bash
      run: |
        echo "Hello"
