name: Pull Request indication
description: This is an action to indicate new pull requestes
branding:
  icon: 'git-pull-request'
  color: 'yellow'

runs:
  using: "composite"
  steps: 
    - name: Indicating new pull request
      shell: bash
      run: |
        echo "Hello, there is new pull request"
        
    - name: Testing loop
      shell: bash
      run: |
        for i in {1..5}
        do
          echo "Welcome $i times"
        done
